/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/features/About.vue')['default']
    AddTodo: typeof import('./src/features/Todos/components/AddTodo.vue')['default']
    App: typeof import('./src/App.vue')['default']
    Artplayer: typeof import('./src/components/Artplayer/Artplayer.vue')['default']
    Button: typeof import('./src/components/Button/Button.vue')['default']
    Contact: typeof import('./src/features/Contact.vue')['default']
    copy: typeof import('./src/features/Todos/page/Todos copy.vue')['default']
    DefaultLayout: typeof import('./src/layouts/DefaultLayout/DefaultLayout.vue')['default']
    Details: typeof import('./src/features/Movie/page/Details/index.vue')['default']
    Footer: typeof import('./src/layouts/components/Footer/Footer.vue')['default']
    Header: typeof import('./src/features/Todos/components/Header.vue')['default']
    HeaderTodo: typeof import('./src/features/Todos/components/HeaderTodo.vue')['default']
    HelloWorld: typeof import('./src/features/Todos/components/HelloWorld.vue')['default']
    Home: typeof import('./src/features/Home/Home.vue')['default']
    Image: typeof import('./src/components/Image/Image.vue')['default']
    Item: typeof import('./src/components/SidebarItem/Item/Item.vue')['default']
    LayoutOnly: typeof import('./src/layouts/LayoutOnly.vue')['default']
    Login: typeof import('./src/layouts/components/Login/Login.vue')['default']
    Main: typeof import('./src/features/Movie/page/Main/index.vue')['default']
    Movie: typeof import('./src/features/Movie/index.vue')['default']
    MovieCard: typeof import('./src/features/Movie/components/MovieCard/index.vue')['default']
    MovieContent: typeof import('./src/features/Movie/components/MovieContent/index.vue')['default']
    MovieControl: typeof import('./src/features/Movie/components/MovieControl/index.vue')['default']
    MovieEpisodes: typeof import('./src/features/Movie/components/MovieEpisodes/index.vue')['default']
    MovieItem: typeof import('./src/features/Movie/components/MovieItem/index.vue')['default']
    MovieList: typeof import('./src/features/Movie/components/MovieList/index.vue')['default']
    MoviePlayer: typeof import('./src/features/Movie/components/MoviePlayer/index.vue')['default']
    MovieRecomened: typeof import('./src/features/Movie/components/MovieRecomened/index.vue')['default']
    MovieServer: typeof import('./src/features/Movie/components/MovieServer/index.vue')['default']
    NewlyAdded: typeof import('./src/features/Movie/page/Sidebar/NewlyAdded/NewlyAdded.vue')['default']
    Paginate: typeof import('./src/components/Paginate/Paginate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/layouts/components/Search/Search.vue')['default']
    Sidebar: typeof import('./src/layouts/components/Sidebar/Sidebar.vue')['default']
    SidebarItem: typeof import('./src/components/SidebarItem/SidebarItem.vue')['default']
    TheAppLayout: typeof import('./src/layouts/TheAppLayout/TheAppLayout.vue')['default']
    Todo: typeof import('./src/features/Todos/components/Todo.vue')['default']
    Todos: typeof import('./src/features/Todos/index.vue')['default']
    'Todos copy': typeof import('./src/features/Todos/page/Todos copy.vue')['default']
    Updated: typeof import('./src/features/Movie/page/Updated/Updated.vue')['default']
  }
}
