/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/features/About.vue')['default']
    AddTodo: typeof import('./src/components/AddTodo.vue')['default']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    App: typeof import('./src/App.vue')['default']
    ASteps: typeof import('ant-design-vue/es')['Steps']
    Button: typeof import('./src/components/Button.vue')['default']
    Contact: typeof import('./src/features/Contact.vue')['default']
    DefaultLayout: typeof import('./src/layouts/DefaultLayout/DefaultLayout.vue')['default']
    Details: typeof import('./src/features/Movie/page/Details/index.vue')['default']
    Footer: typeof import('./src/layouts/components/Footer/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HeaderTodo: typeof import('./src/components/HeaderTodo.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/features/Home/Home.vue')['default']
    Item: typeof import('./src/components/SidebarItem/Item/Item.vue')['default']
    LayoutOnly: typeof import('./src/layouts/LayoutOnly.vue')['default']
    Layouts: typeof import('./src/layouts/index.vue')['default']
    Main: typeof import('./src/features/Movie/page/Main/index.vue')['default']
    Movie: typeof import('./src/features/Movie/index.vue')['default']
    MovieCard: typeof import('./src/features/Movie/components/MovieCard/index.vue')['default']
    MovieContent: typeof import('./src/features/Movie/components/MovieContent/index.vue')['default']
    MovieControl: typeof import('./src/features/Movie/components/MovieControl/index.vue')['default']
    MovieEpisodes: typeof import('./src/features/Movie/components/MovieEpisodes/index.vue')['default']
    MovieEposodes: typeof import('./src/features/Movie/components/MovieEposodes/index.vue')['default']
    MovieItem: typeof import('./src/features/Movie/components/MovieItem/index.vue')['default']
    MovieList: typeof import('./src/features/Movie/components/MovieList/index.vue')['default']
    MoviePlayer: typeof import('./src/features/Movie/components/MoviePlayer/index.vue')['default']
    MovieRecomened: typeof import('./src/features/Movie/components/MovieRecomened/index.vue')['default']
    MovieServer: typeof import('./src/features/Movie/components/MovieServer/index.vue')['default']
    NewlyAdded: typeof import('./src/features/Movie/page/Sidebar/NewlyAdded/NewlyAdded.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/layouts/components/Search/Search.vue')['default']
    Sidebar: typeof import('./src/layouts/components/Sidebar/Sidebar.vue')['default']
    SidebarItem: typeof import('./src/components/SidebarItem/SidebarItem.vue')['default']
    Siderbar: typeof import('./src/components/SidebarItem/Siderbar.vue')['default']
    SiderBar: typeof import('./src/components/Sidebar/SiderBar.vue')['default']
    TheAppLayout: typeof import('./src/layouts/TheAppLayout/TheAppLayout.vue')['default']
    Todo: typeof import('./src/components/Todo.vue')['default']
    Todos: typeof import('./src/components/Todos.vue')['default']
    Updated: typeof import('./src/features/Movie/page/Updated/Updated.vue')['default']
    Watch: typeof import('./src/features/Movie/page/Watch/index.vue')['default']
  }
}
